#!/bin/bash
# Run hilltop

# Make sure we're groovy enough
which groovy > /dev/null || echo "Cannot find groovy"

# Setup the environment
[ -z $HILLTOP_HOME ] && HILLTOP_HOME="."
CLASSPATH="$HILLTOP_HOME/src/main/groovy:$HILLTOP_HOME/build/hilltop-dependencies.jar:$CLASSPATH"
export HILLTOP_HOME CLASSPATH

# Start hilltop
# groovy -cp ./src/main/groovy hilltop.groovy
groovy $HILLTOP_HOME/hilltop.groovy $@
