#!/bin/bash

# Make sure we're groovy enough
which groovy > /dev/null || echo "Cannot find groovy"

# Join arguments
printf -v var "'%s', " "$@"

# Remove trailing ", "
var=${var%??}

# run via Gradle
gradle run -Pcommand="[$var]"
